# Generated by Django 5.2.17 on 2026-08-05 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_rename_items_item'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Item',
            new_name='Items',
        ),
    ]
